<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <PropertyGroup>
        <PackageDir>$(ProjectDir)Package\</PackageDir>
        <MergedAssemblyFile>$(PackageDir)$(AssemblyName).dll</MergedAssemblyFile>
        <PublishDir>$(SolutionDir)PublishOutput\</PublishDir>
        <ReadmeFile>$(SolutionDir)README.md</ReadmeFile>
        <ManifestFile>$(ProjectDir)manifest.json</ManifestFile>
        <IconFile>$(ProjectDir)icon.png</IconFile>
        <ChangelogFile>$(ProjectDir)CHANGELOG.md</ChangelogFile>
        <LicenseFile>$(SolutionDir)LICENSE</LicenseFile>
    </PropertyGroup>

    <ItemGroup>
        <SourceFiles Include="$(ReadmeFile);$(ManifestFile);$(IconFile);$(ChangelogFile);$(LicenseFile)"/>
        <DebugFiles Include="$(TargetDir)\*.*"/>
    </ItemGroup>
</Project>