<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Target Name="ILRepacker" AfterTargets="AfterBuild">
        <ItemGroup>
            <InputAssemblies Include="$(TargetPath)" />
            <InputAssemblies Include="$(ProjectDir)lib\ServerSync.dll" />
        </ItemGroup>
        <ILRepack 
                Parallel="true" 
                DebugInfo="true" 
                Internalize="true" 
                InputAssemblies="@(InputAssemblies)" 
                OutputFile="$(ProjectDir)Package\ValheimReelableHarpoon.dll"
                TargetKind="SameAsPrimaryAssembly" 
                LibraryPath="$(ProjectDir)lib\" 
        />
    </Target>
</Project>