<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
    <Import Project="$(ProjectDir)Environment.props"/>
    <Import Project="$(ProjectDir)Local.Environment.props"/>
    
    <Target Name="ILRepacker" AfterTargets="AfterBuild">
        <ItemGroup>
            <InputAssemblies Include="$(TargetPath)" />
            <InputAssemblies Include="$(ProjectDir)lib\ServerSync.dll" />
        </ItemGroup>
        <ILRepack
                Parallel="true" 
                DebugInfo="true" 
                Internalize="true" 
                InputAssemblies="@(InputAssemblies)"
                OutputFile="$(TargetPath)"
                TargetKind="SameAsPrimaryAssembly" 
                LibraryPath="$(ProjectDir)lib\"/>
    </Target>
    
    <Target Name="Debug" 
            AfterTargets="ILRepacker" 
            Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
        
        <RemoveDir Directories="$(BuildDir)" Condition="Exists('$(BuildDir)')"/>
        <MakeDir Directories="$(BuildDir)"/>
        <Delete Files="$(TargetPath).mdb" Condition="Exists('$(TargetPath).mdb')"/>
        <Exec Command="$(SolutionDir)pdb2mdb.exe $(TargetPath)" />
        <Copy SourceFiles="@(DebugFiles)" DestinationFolder="$(BuildDir)"/>
        <Copy SourceFiles="$(TargetPath).mdb" DestinationFolder="$(BuildDir)"/>
        <Message Text="Copied $(TargetDir) to $(BuildDir)." Importance="high"/>
    </Target>
    
    <Target Name="Release" 
            AfterTargets="ILRepacker" 
            Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">

        <MakeDir Directories="$(PackageDir)" Condition="!Exists('$(PackageDir)')"/>
        <MakeDir Directories="$(PublishDir)" Condition="!Exists('$(PublishDir)')"/>
        <Copy SourceFiles="@(SourceFiles)" DestinationFolder="$(PackageDir)"/>
        <Message Text="Copied @(SourceFiles) to $(PackageDir)."/>
        <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(PackageDir)"/>
        <Message Text="Copied $(TargetPath) to $(PackageDir)."/>
        <ZipDirectory SourceDirectory="$(PackageDir)" DestinationFile="$(PublishDir)$(AssemblyName).zip" Overwrite="true"/>
        <RemoveDir Directories="$(BuildDir)" Condition="Exists('$(BuildDir)')"/>
    </Target>
</Project>